apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  DB_PASSWORD: your_database_password
  JWT_SECRET: your_jwt_secret

  RABBITMQ_USERNAME: your_rabbitmq_username
  RABBITMQ_PASSWORD: your_rabbitmq_password