server.port=8080

eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka

eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,gateway,prometheus

management.endpoint.gateway.access=unrestricted

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[2].id=product-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/products/**

spring.cloud.gateway.server.webflux.routes[3].id=inventory-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/inventory/**

spring.cloud.gateway.server.webflux.routes[4].id=order-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.server.webflux.routes[5].id=payment-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/payments/**

spring.cloud.gateway.server.webflux.routes[6].id=notification-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.server.webflux.routes[7].id=review-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://review-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/reviews/**