name: Kubernetes Connection Test

on:
  workflow_dispatch:

jobs:
  test-kubernetes:
    runs-on: self-hosted

    steps:
      - name: Check kubectl
        run: kubectl version --client

      - name: Check Kubernetes cluster
        run: kubectl get nodes

      - name: Check ecommerce namespace
        run: kubectl get pods -n ecommerce